### ISSUE TITLE
Remove `MESSAGE` and `BEGIN`/`END` from diff

### ISSUE THREAD

**Issue by soedirgo** [supabase/pgadmin4#11]
Better to leave txn-wrapping to the user, e.g. the Supabase CLI automatically wraps migration files with `BEGIN`/`END`.

**Comment by steve-chavez** [comment]
This one should be simple. The BEGIN/END are added here: 

https://github.com/supabase/pgadmin4/blob/5dcd30f188fd4f107f51d4e3ab7dfe661383ba80/web/cli.py#L356-L363

I did that to be compliant with the pgadmin GUI output(also adds BEGIN/END to the diff).
