### ISSUE TITLE
Rebase `cli` onto `master` & release cli-0.0.3

### ISSUE THREAD

**Issue by soedirgo** [supabase/pgadmin4#12]

**Comment by soedirgo** [comment]
Might want to update `master` again, there are 100+ new commits.

**Comment by soedirgo** [comment]
@steve-chavez @olirice can we release this? Need to test out a bug.

**Comment by steve-chavez** [comment]
@soedirgo Hm, what's the action here? You mean create a new tag?

**Comment by steve-chavez** [comment]
@soedirgo Done! Just pushed https://github.com/supabase/pgadmin4/releases/tag/cli-0.0.3

**Comment by soedirgo** [comment]
Thanks! Just realized the CI is set up to push to Docker on tag.
